name: Deploy to Azure

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME_API: 'prestigeapi'
  AZURE_WEBAPP_NAME_WEB: 'PrestigeWeb'
  DOTNET_VERSION: '9.0.x'
  NODE_VERSION: '20.14.0'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      web: ${{ steps.filter.outputs.web }}
      api: ${{ steps.filter.outputs.api }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          web:
            - 'Prestige.Web/**'
            - '.github/workflows/deploy.yml'
          api:
            - 'Prestige.Api/**'
            - '.github/workflows/deploy.yml'
  build-and-deploy-api:
    needs: changes
    if: needs.changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build API
      run: dotnet build Prestige.Api/*.csproj --configuration Release --no-restore
      
    - name: Publish API
      run: dotnet publish Prestige.Api/*.csproj --configuration Release --no-build --output ./api-publish
      
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_API }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        package: ./api-publish

  build-and-deploy-web:
    needs: changes
    if: needs.changes.outputs.web == 'true'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: ./Prestige.Web/yarn.lock
        
    - name: Enable Corepack
      run: corepack enable
      
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      working-directory: ./Prestige.Web
      
    - name: Build application
      run: yarn build
      working-directory: ./Prestige.Web
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME_WEB }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
        package: ./Prestige.Web/dist